# Bukkit delete none Header Comments when saving the yml file
# To see the deleted comments, go to the github repository and find unter resource the config file
bStats:
  # Disable/Enable BStats. bStats is on the first start of the server disabled to generate this file
  enable: true
server:
  # Restart: Commands or files (!file <File>) or commands (!run <Command>) to be executed when restarting
  restart:
  - stop
  # PlayerAmount showen in Main Screen.
  # -1 = disable
  # if the current online Players > showPlayerAmount the players, who tried to join, will be kicked
  # In this case only operators or players in joinPlayersWhenFull can join on the server
  showPlayerAmount: -1
  # Kick Message if the server is full
  fullMessage: ยง4The Server is full
  # See showPlayerAmount
  joinPlayersWhenFull:
  - UUID
  # This can disable/enable couldOperator
  enableOperator: false
  # Only these players could be operators. If a none-player get op and tried to use command, the op state will be removed.
  couldOperator:
  - UUID
  # False: Use the standart motd of the server. True: use this motd in this config.
  # If you use the command
  motd-enable: false
  # Set the motd Text of the Server
  motd: ยง4Error 404 Message is missing
