name: Allgemein
version: 0.4.beta
author: JJ
main: essentials.main.Main
api-version: 1.13

commands:
     all:
          description: allgemein
     trol:
          description: Trol Plugin
          permission: trol.all
     cv:
          description: ChatVerbesserung
          permission: ChatV.use
     cos:
          description: CommandonBlocks
     post:
          description: Post/Chest open
          permission: post.use