name: CBM
version: 0.4.2.beta
author: JJ
main: essentials.main.Main
api-version: 1.13

commands:
     cbm:
          description: allgemein
     trol:
          description: Trol Plugin
          permission: trol.all
     cv:
          description: ChatVerbesserung
          permission: ChatV.use
     post:
          description: Post/Chest open
          permission: post.use